name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/vue-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint:oxlint

      - name: Formatting
        run: npm run format

      - name: Testing
        run: npm run test:unit

      - name: Building
        run: npm run build

      - name: Deploying to non-prod
        run: echo "Deploying..."
